var D_CITY='Milano';var D_CITY_LONG='Milano, MI Italia';var ERR_PERM='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var ERR_POS_DEN='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var ERR_TIMEOUT='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var categories=[];json=readCookie(CACHED_CATEGORIES);if(json!="")categories=$.parseJSON("["+json+"]");if(categories.length<=1)
$.getJSON("/api/v2/categories-macro-tags",{term:""},function(data){while(categories.length){categories.pop();}
$.each(data,function(i,cat){categories.push(JSON.stringify({"name":cat.catName,"img":cat.img}));});createCookie(CACHED_CATEGORIES,categories,7);categories=$.parseJSON("["+categories+"]");populateList();});var animationEvent=whichAnimationEvent();$(".pallino").click(function(){$("#willBounce").addClass("bouncing");$(this).one(animationEvent,function(e){$("#willBounce").removeClass("bouncing");});});function whichAnimationEvent(){var t,el=document.createElement("fakeelement");var animations={"animation":"animationend","OAnimation":"oAnimationEnd","MozAnimation":"animationend","WebkitAnimation":"webkitAnimationEnd"};for(t in animations)if(el.style[t]!==undefined)return animations[t];}
$(function(){$("#datepicker").datepicker({dateFormat:'dd/mm/yy'});});populateList();jQuery(document).ready(function(){setHeight();if(!is_Mobile){eventCustomAutocomplete(".event-autocomplete",function(val,elem){},"#event-suggestions","#eventSeoUrl","#eventCategory",".search-button");cityCustomAutocomplete(".city-autocomplete",function(val,elem){},"#city-suggestions",".search-button");cityCustomAutocomplete(".city-only-autocomplete",function(val,elem){},"#city-only-suggestions",".search-only-button");$(".event-autocomplete").val("");$(".city-autocomplete").val(currentLocation.name);}});function setHeight(){var windowHeight=$(window).innerHeight();var headerHeight=$('.navbar').height();if(!is_Mobile){$('.background').css('height',windowHeight-headerHeight);}
$('.index_page_search').css('height',windowHeight-headerHeight);}
$(window).resize(function(){setHeight();});function populateList(){var LIST=$("#mobileUlList");$.each(categories,function(index,value){var $li=$("<li class='list-group-item noselect col-xs-12'></li>");$li.text(value.name.capitalize());var $i="<img src='"+value.img+"'>";$li.prepend($i);$li.on('click',function(e){category=value.name;getMobileLocation();});LIST.append($li);});}
function getMobileLocation(){console.log("asking for geoloc permissions");var options={enableHighAccuracy:false,maximumAge:0,timeout:1000};if(navigator&&navigator.geolocation){navigator.geolocation.getCurrentPosition(showMobilePosition,showMobileError,options);}else{console.log("Geolocation is not supported by this browser.");showMobileError();}}
function showMobileError(error){var confirmText=ERR_PERM;if(error.code==error.POSITION_UNAVAILABLE)confirmText=ERR_POS_DEN;else if(error.code==error.TIMEOUT)confirmText=ERR_TIMEOUT;if(confirm(confirmText))categoryRedirect(D_CITY.lower());else console.error('User declined geolocation permission, and then refused default '+D_CITY+' search also');}
function showMobilePosition(position){var url="/api/v2/city-by-coord?lat="+position.coords.latitude+"&lon="+position.coords.longitude;jQuery.ajax({url:url,success:function(html){loaded=true;var obj=html[0];currentLocationHName=obj.name.lower();var url="/eventi/"+obj.name.lower()+"/"+category;$(location).attr("href",url);},error:function(error){showMobileError();},async:false});}
function categoryRedirect(city){currentLocationHName=city;var url="/eventi/"+city.lower()+"/"+category;$(location).attr("href",url);}