var SPINNER=$(".autocomplete-spinner");var EVENT=$('.event-autocomplete');var CITY=$(".city-same-text");var D_CITY='Milano';var D_CITY_LONG='Milano, MI Italia';var ERR_PERM='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var ERR_POS_DEN='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var ERR_TIMEOUT='Eventa non ha i permessi necessari per determinare la tua posizione. Vuoi cercare eventi a '+D_CITY_LONG+'?';var RECENT_LOCATION="recentlocation";var LOCATION="location";var CACHED_CATEGORIES="categories";var RECENT_LOCATIONS_N=5;var GEOLOC_LABEL="Posizione corrente";var json;var lat=0.0;var lon=0.0;var radius=0.0;var recentLocations=[];json=readCookie(RECENT_LOCATION);if(json!="")recentLocations=$.parseJSON(json);var currentLocation=[];json=readCookie(LOCATION)
if(json!="")currentLocation=$.parseJSON(json);if(currentLocation!=null){if(currentLocation.length==0){currentLocation={"name":"Milano","lat":45.4642700,"lon":9.1895100,"radius":50.0};createCookie(LOCATION,JSON.stringify(currentLocation));}}
lat=currentLocation.lat;lon=currentLocation.lon;radius=currentLocation.radius;var categories=[];json=readCookie(CACHED_CATEGORIES);if(json!="")categories=$.parseJSON("["+json+"]");if(categories.length<=1)
$.getJSON("/api/v2/categories-macro-tags",{term:""},function(data){while(categories.length){categories.pop();}
$.each(data,function(i,cat){categories.push(JSON.stringify({"name":cat.catName,"img":cat.img}));});createCookie(CACHED_CATEGORIES,categories,7);categories=$.parseJSON("["+categories+"]");});function eventCustomAutocomplete(sel,select,appendTo,ev_sup,cat_sup,searchButton){var searchButton=$(searchButton);var search=$(sel);var events=[];var eventIds=[];var eventCategory=[];var populated=false;var EVENT_TYPE="event";var CAT_TYPE="category";var EVENT_SUPPORT=$(ev_sup);var CAT_SUPPORT=$(cat_sup);if(!is_Mobile)search.focus();var eventAutocomplete=search.autocomplete({source:function(request,response){while(eventCategory.length){eventCategory.pop();}
while(eventIds.length){eventIds.pop();}
while(events.length){events.pop();}
if(request.term.length>=4){SPINNER.show();$.getJSON("/api/v2/event-or-category",{lat:lat,lon:lon,radius:radius,term:request.term.trim()},function(data){SPINNER.hide();var suggestions=[];$.each(data,function(i,val){if(val.seoUrl!=null){suggestions.push({"type":EVENT_TYPE,"value":val.title.capitalize().trimText(50),"venue":val.venue,"seoUrl":val.seoUrl});eventIds.push(val.seoUrl);}else{suggestions.push({"type":CAT_TYPE,"value":val.name.capitalize(),"img":val.img});eventCategory.push(val.name.capitalize());}});response(suggestions);$.each(suggestions,function(i,c){events.push(c.value.trim().substring(0,20));});}).fail(function(){console.error("ERRORE NELLA CHIAMATA EVENTI-O-CATEGORIE");SPINNER.hide();});}else{$.each(categories.filter(function(item){return(request.term.length==0||item.name.lower().indexOf(request.term.lower())!=-1);}),function(i,val){events.push({"type":CAT_TYPE,"value":val.name.capitalize(),"img":val.img});eventCategory.push(val.name.capitalize());});response(events);}},minLength:0,appendTo:appendTo,select:function(event,ui){if(ui.item.type==CAT_TYPE)populateEvent(CAT_TYPE,ui.item.value,null);else populateEvent(EVENT_TYPE,ui.item.value,ui.item.seoUrl);event.preventDefault();}}).data("ui-autocomplete");eventAutocomplete._renderItem=function(ul,item){var $a=$("<a></a>").text(item.label);var $i=null;var c="";if(item.type==EVENT_TYPE){c=EVENT_TYPE;$a.append("<label>"+item.venue+"</label>");}else if(item.type==CAT_TYPE){c=CAT_TYPE;$i="<i><img src='"+item.img+"'></i>";}
highlightText(this.term,$a);return $("<li></li>").addClass(c).prepend($i).append($a).appendTo(ul);};search.keydown(function(e){EVENT_SUPPORT.val("");CAT_SUPPORT.val("");populated=false;});search.on("click",function(){$(this).select();var uid=$("#"+eventAutocomplete.bindings[1].id);if(uid.html().length==0){$(this).keydown();}
else{uid.show();}});searchButton.on("click",function(){if(!populated)populateEvent(null,search.val(),null);});var populateEvent=function(type,value,seoUrl){populated=true;search.val(value);if(type==CAT_TYPE){console.log("UPDATING CATEGORY SUPPORT ",value.lower());CAT_SUPPORT.val(value.lower());console.log(CAT_SUPPORT.val());searchButton.click();}else if(type==EVENT_TYPE){console.log("UPDATING EVENT SUPPORT ",seoUrl.lower());EVENT_SUPPORT.val(seoUrl.lower());searchButton.click();}else searchButton.click();}}
function cityCustomAutocomplete(sel,select,appendTo,searchButton){var searchButton=$(searchButton);var search=$(sel);var cities=[];var populated=false;var HEADER_TYPE="header";var PLACE_TYPE="place";var HISTORY_TYPE="history";var cityAutocomplete=search.autocomplete({source:function(request,response){if(request.term.length>2){$.getJSON("/api/v2/cities",{term:request.term.trim()},function(data){var suggestions=[];suggestions.push({"type":HEADER_TYPE,"name":GEOLOC_LABEL});$.each(data,function(i,val){suggestions.push({"type":PLACE_TYPE,"name":val.name.capitalize(),"lat":val.lat,"lon":val.lon,"radius":val.radius});});while(cities.length){cities.pop();}
response(suggestions);$.each(suggestions,function(i,c){cities.push(c.name.lower().trim());});})}else{var staticCities=[];staticCities.push({"type":HEADER_TYPE,"name":GEOLOC_LABEL});$.each(recentLocations.filter(function(item){return(request.term.length==0||item.name.lower().indexOf(request.term.lower())!=-1);}),function(i,val){if(val.name!="")staticCities.push({"type":HISTORY_TYPE,"name":val.name.capitalize(),"lat":val.lat,"lon":val.lon,"radius":val.radius});});response(staticCities);}},minLength:0,appendTo:appendTo,select:function(event,ui){lat=ui.item.lat;lon=ui.item.lon;radius=ui.item.radius;if(ui.item.name.lower()==GEOLOC_LABEL.lower())return false;if(ui.item!==undefined&&(ui.item.name.lower()!=GEOLOC_LABEL.lower())){populateCity(ui.item.name.trim(),lat,lon,radius);}
CITY.val(ui.item.name.trim());event.preventDefault();}}).data("ui-autocomplete");cityAutocomplete._renderItem=function(ul,item){var $a=$("<a></a>").text(item.name);var $i=null;var $r=$("<li></li>");var c="";if(item.type==HEADER_TYPE){c=HEADER_TYPE;$i="<i class='fa fa-location-arrow'></i>";$r.bind('click',function(){getLocation();});}else if(item.type==HISTORY_TYPE){c=HISTORY_TYPE;$i="<i class='fa fa-history'></i>";}else{c=PLACE_TYPE;}
highlightText(this.term,$a);return $r.addClass(c).prepend($i).append($a).appendTo(ul);}
search.on("click",function(){$(this).select();var uid=$("#"+cityAutocomplete.bindings[1].id);if(uid.html().length==0){$(this).keydown();}
else{uid.show();}
search.autocomplete('search','');});searchButton.on("click",function(){if(!populated){populateCity(search.val(),lat,lon,radius);}
CITY.val(currentLocation.name);});var populateCity=function(value,lat,lon,radius){console.log("POPULATING CITY");populated=true;if(value!=""){currentLocation={"name":value,"lat":lat,"lon":lon,"radius":radius};createCookie(LOCATION,JSON.stringify(currentLocation));var mustAdd=true;$.each(recentLocations,function(index,value){mustAdd=mustAdd&&value.name.lower()!=currentLocation.name.lower();});if(mustAdd&&value!=""&&value!=GEOLOC_LABEL){console.log("added: "+currentLocation.name+" to recentLocations");recentLocations.push(currentLocation);}
if(recentLocations.length>RECENT_LOCATIONS_N){console.log("removed first element to recentLocations before adding");recentLocations.shift();}
createCookie(RECENT_LOCATION,JSON.stringify(recentLocations));}
if(EVENT.val()!="")searchButton.click();}
function getLocation(){var options={enableHighAccuracy:false,maximumAge:0,timeout:1000};if(navigator&&navigator.geolocation){navigator.geolocation.getCurrentPosition(showPosition,showError,options);}else{console.error("Geolocation is not supported by this browser.");showError(1);}}
function showError(error){var confirmText=ERR_PERM;if(error.code==error.POSITION_UNAVAILABLE)confirmText=ERR_POS_DEN;else if(error.code==error.TIMEOUT)confirmText=ERR_TIMEOUT;if(confirm(confirmText)){lat=45.4642700;lon=9.1881263;radius=50.0;populateCity(D_CITY,lat,lon,radius);CITY.val(D_CITY);}
else console.error('User declined geolocation permission, and then refused default '+D_CITY+' search also');}
function showPosition(position){var url="/api/v2/city-by-coord?lat="+position.coords.latitude+"&lon="+position.coords.longitude;jQuery.ajax({url:url,success:function(html){loaded=true;var obj=html[0];lat=obj.lat;lon=obj.lon;radius=obj.radius;populateCity(obj.name,obj.lat,obj.lon,obj.radius);CITY.val(obj.name);},error:function(error){showError();},async:true});}}
function highlightText(text,$node){var searchText=$.trim(text).lower(),currentNode=$node.get(0).firstChild,matchIndex,newTextNode,newSpanNode;if(currentNode.data==null)currentNode=$node.get(0).childNodes[1];if(searchText==""||currentNode.data==null)return;while((matchIndex=currentNode.data.lower().indexOf(searchText))>=0){newTextNode=currentNode.splitText(matchIndex);currentNode=newTextNode.splitText(searchText.length);newSpanNode=document.createElement("span");newSpanNode.className="highlight";currentNode.parentNode.insertBefore(newSpanNode,currentNode);newSpanNode.appendChild(newTextNode);}}